/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AffectationsPdvModal: typeof import('./src/components/parametrage/AffectationsPdvModal.vue')['default']
    AppConfirmDialog: typeof import('./src/components/AppConfirmDialog.vue')['default']
    CanalVenteFormModal: typeof import('./src/components/catalogue/CanalVenteFormModal.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ChangerMotDePasseModal: typeof import('./src/components/parametrage/ChangerMotDePasseModal.vue')['default']
    CommandeFournisseurFormModal: typeof import('./src/components/achats/CommandeFournisseurFormModal.vue')['default']
    CompteComptableFormModal: typeof import('./src/components/comptabilite/CompteComptableFormModal.vue')['default']
    CompteTresorerieFormModal: typeof import('./src/components/tresorerie/CompteTresorerieFormModal.vue')['default']
    ConditionnementFormModal: typeof import('./src/components/catalogue/ConditionnementFormModal.vue')['default']
    ContactFormModal: typeof import('./src/components/partenaires/ContactFormModal.vue')['default']
    DepotFormModal: typeof import('./src/components/achats/DepotFormModal.vue')['default']
    DeviseFormModal: typeof import('./src/components/parametrage/DeviseFormModal.vue')['default']
    EntrepriseFormModal: typeof import('./src/components/parametrage/EntrepriseFormModal.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FactureFournisseurFormModal: typeof import('./src/components/achats/FactureFournisseurFormModal.vue')['default']
    FamilleProduitFormModal: typeof import('./src/components/catalogue/FamilleProduitFormModal.vue')['default']
    JournalComptableFormModal: typeof import('./src/components/comptabilite/JournalComptableFormModal.vue')['default']
    ModePaiementFormModal: typeof import('./src/components/tresorerie/ModePaiementFormModal.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PeriodeComptableFormModal: typeof import('./src/components/comptabilite/PeriodeComptableFormModal.vue')['default']
    PermissionFormModal: typeof import('./src/components/parametrage/PermissionFormModal.vue')['default']
    PermissionsRoleModal: typeof import('./src/components/parametrage/PermissionsRoleModal.vue')['default']
    PointDeVenteFormModal: typeof import('./src/components/parametrage/PointDeVenteFormModal.vue')['default']
    ProduitDetailModal: typeof import('./src/components/catalogue/ProduitDetailModal.vue')['default']
    ProduitFormModal: typeof import('./src/components/catalogue/ProduitFormModal.vue')['default']
    ReceptionFormModal: typeof import('./src/components/achats/ReceptionFormModal.vue')['default']
    ReglementFormModal: typeof import('./src/components/tresorerie/ReglementFormModal.vue')['default']
    RoleFormModal: typeof import('./src/components/parametrage/RoleFormModal.vue')['default']
    RolesPermissionModal: typeof import('./src/components/parametrage/RolesPermissionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TauxChangeFormModal: typeof import('./src/components/parametrage/TauxChangeFormModal.vue')['default']
    TauxTvaFormModal: typeof import('./src/components/catalogue/TauxTvaFormModal.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TiersFormModal: typeof import('./src/components/partenaires/TiersFormModal.vue')['default']
    ToastSnackbar: typeof import('./src/components/ToastSnackbar.vue')['default']
    TypeTiersFormModal: typeof import('./src/components/partenaires/TypeTiersFormModal.vue')['default']
    UniteMesureFormModal: typeof import('./src/components/catalogue/UniteMesureFormModal.vue')['default']
    UtilisateurFormModal: typeof import('./src/components/parametrage/UtilisateurFormModal.vue')['default']
  }
}
