"""autogenerate_schema

Revision ID: e713e26e2ee7
Revises: 
Create Date: 2026-02-18 12:12:24.233505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e713e26e2ee7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('symbole', sa.String(length=10), nullable=True),
    sa.Column('decimales', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devises_code'), 'devises', ['code'], unique=True)
    op.create_table('entreprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=True),
    sa.Column('niu', sa.String(length=20), nullable=True),
    sa.Column('regime_fiscal', sa.String(length=30), nullable=False),
    sa.Column('mode_gestion', sa.String(length=30), nullable=False),
    sa.Column('forme_juridique', sa.String(length=30), nullable=True),
    sa.Column('rccm', sa.String(length=50), nullable=True),
    sa.Column('cnps', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('boite_postale', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=3), nullable=False),
    sa.Column('fuseau_horaire', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('devise_principale', sa.String(length=3), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entreprises_code'), 'entreprises', ['code'], unique=True)
    op.create_index(op.f('ix_entreprises_niu'), 'entreprises', ['niu'], unique=False)
    op.create_table('etats_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_document', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etats_document_code'), 'etats_document', ['code'], unique=False)
    op.create_index(op.f('ix_etats_document_type_document'), 'etats_document', ['type_document'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'action', name='uq_permissions_module_action')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('taux_tva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('taux', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taux_tva_code'), 'taux_tva', ['code'], unique=True)
    op.create_table('types_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_tiers_code'), 'types_tiers', ['code'], unique=True)
    op.create_table('unites_mesure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('symbole', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('code_cefact', sa.String(length=10), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unites_mesure_code'), 'unites_mesure', ['code'], unique=True)
    op.create_table('canaux_vente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_canaux_vente_entreprise_code')
    )
    op.create_index(op.f('ix_canaux_vente_code'), 'canaux_vente', ['code'], unique=False)
    op.create_table('categories_immobilisation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('duree_amortissement_annees', sa.Integer(), nullable=False),
    sa.Column('taux_amortissement', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_categories_immobilisation_entreprise_code')
    )
    op.create_index(op.f('ix_categories_immobilisation_code'), 'categories_immobilisation', ['code'], unique=False)
    op.create_table('comptes_comptables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('type_compte', sa.String(length=20), nullable=True),
    sa.Column('sens_normal', sa.String(length=10), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'numero', name='uq_comptes_comptables_entreprise_numero')
    )
    op.create_index(op.f('ix_comptes_comptables_numero'), 'comptes_comptables', ['numero'], unique=False)
    op.create_table('comptes_tresorerie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('type_compte', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('numero_compte', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('devise_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'libelle', name='uq_comptes_tresorerie_entreprise_libelle')
    )
    op.create_table('conditionnements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('quantite_unites', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unite_id', sa.Integer(), nullable=False),
    sa.Column('type_emballage', sa.String(length=30), nullable=True),
    sa.Column('poids_net_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['unite_id'], ['unites_mesure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditionnements_code'), 'conditionnements', ['code'], unique=False)
    op.create_table('departements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('centre_cout', sa.String(length=30), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_departements_entreprise_code')
    )
    op.create_index(op.f('ix_departements_code'), 'departements', ['code'], unique=False)
    op.create_table('familles_produits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['familles_produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familles_produits_code'), 'familles_produits', ['code'], unique=False)
    op.create_table('journaux_comptables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_journaux_comptables_entreprise_code')
    )
    op.create_table('licences_logicielles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('cle_licence', sa.String(length=35), nullable=False),
    sa.Column('type_licence', sa.String(length=30), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('nombre_prolongations', sa.Integer(), nullable=False),
    sa.Column('date_activation', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'cle_licence', name='uq_licences_logicielles_entreprise_cle')
    )
    op.create_index(op.f('ix_licences_logicielles_cle_licence'), 'licences_logicielles', ['cle_licence'], unique=False)
    op.create_table('modes_paiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('code_operateur', sa.String(length=30), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_modes_paiement_entreprise_code')
    )
    op.create_table('parametres_systeme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('cle', sa.String(length=80), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'categorie', 'cle', name='uq_parametres_systeme_ent_cat_cle')
    )
    op.create_index(op.f('ix_parametres_systeme_categorie'), 'parametres_systeme', ['categorie'], unique=False)
    op.create_index(op.f('ix_parametres_systeme_cle'), 'parametres_systeme', ['cle'], unique=False)
    op.create_table('periodes_comptables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('cloturee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'date_debut', name='uq_periodes_comptables_entreprise_debut')
    )
    op.create_table('periodes_paie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('cloturee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'annee', 'mois', name='uq_periodes_paie_entreprise_annee_mois')
    )
    op.create_table('points_de_vente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('fuseau_horaire', sa.String(length=50), nullable=True),
    sa.Column('est_depot', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_points_de_vente_entreprise_code')
    )
    op.create_index(op.f('ix_points_de_vente_code'), 'points_de_vente', ['code'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_table('taux_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devise_from_id', sa.Integer(), nullable=False),
    sa.Column('devise_to_id', sa.Integer(), nullable=False),
    sa.Column('taux', sa.Float(), nullable=False),
    sa.Column('date_effet', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devise_from_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['devise_to_id'], ['devises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taux_commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('taux_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_taux_commissions_entreprise_code')
    )
    op.create_table('types_conge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('paye', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_types_conge_entreprise_code')
    )
    op.create_index(op.f('ix_types_conge_code'), 'types_conge', ['code'], unique=False)
    op.create_table('types_contrat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_types_contrat_entreprise_code')
    )
    op.create_index(op.f('ix_types_contrat_code'), 'types_contrat', ['code'], unique=False)
    op.create_table('types_element_paie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_types_element_paie_entreprise_code')
    )
    op.create_index(op.f('ix_types_element_paie_code'), 'types_element_paie', ['code'], unique=False)
    op.create_table('depots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('pays', sa.String(length=3), nullable=True),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_code'), 'depots', ['code'], unique=False)
    op.create_table('immobilisations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('compte_comptable_id', sa.Integer(), nullable=True),
    sa.Column('compte_amortissement_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('date_acquisition', sa.Date(), nullable=False),
    sa.Column('valeur_acquisition', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('duree_amortissement_annees', sa.Integer(), nullable=False),
    sa.Column('date_mise_en_service', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_immobilisation.id'], ),
    sa.ForeignKeyConstraint(['compte_amortissement_id'], ['comptes_comptables.id'], ),
    sa.ForeignKeyConstraint(['compte_comptable_id'], ['comptes_comptables.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_immobilisations_entreprise_code')
    )
    op.create_index(op.f('ix_immobilisations_code'), 'immobilisations', ['code'], unique=False)
    op.create_table('permissions_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_permissions_roles_role_permission')
    )
    op.create_table('postes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_postes_entreprise_code')
    )
    op.create_index(op.f('ix_postes_code'), 'postes', ['code'], unique=False)
    op.create_table('produits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('famille_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('code_barre', sa.String(length=50), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('marque', sa.String(length=80), nullable=True),
    sa.Column('reference_fournisseur', sa.String(length=80), nullable=True),
    sa.Column('code_douanier', sa.String(length=20), nullable=True),
    sa.Column('pays_origine', sa.String(length=3), nullable=True),
    sa.Column('poids_net_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unite_vente_id', sa.Integer(), nullable=False),
    sa.Column('unite_achat_id', sa.Integer(), nullable=True),
    sa.Column('coefficient_achat_vente', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('prix_achat_ht', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('prix_vente_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taux_tva_id', sa.Integer(), nullable=True),
    sa.Column('seuil_alerte_min', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('seuil_alerte_max', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('gerer_stock', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['famille_id'], ['familles_produits.id'], ),
    sa.ForeignKeyConstraint(['taux_tva_id'], ['taux_tva.id'], ),
    sa.ForeignKeyConstraint(['unite_achat_id'], ['unites_mesure.id'], ),
    sa.ForeignKeyConstraint(['unite_vente_id'], ['unites_mesure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_code'), 'produits', ['code'], unique=False)
    op.create_index(op.f('ix_produits_code_barre'), 'produits', ['code_barre'], unique=False)
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('type_tiers_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=True),
    sa.Column('nom_contact', sa.String(length=150), nullable=True),
    sa.Column('niu', sa.String(length=20), nullable=True),
    sa.Column('rccm', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('boite_postale', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=3), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('telephone_secondaire', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('canal_vente_id', sa.Integer(), nullable=True),
    sa.Column('limite_credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('delai_paiement_jours', sa.Integer(), nullable=True),
    sa.Column('compte_bancaire', sa.String(length=50), nullable=True),
    sa.Column('mobile_money_numero', sa.String(length=20), nullable=True),
    sa.Column('mobile_money_operateur', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canal_vente_id'], ['canaux_vente.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['type_tiers_id'], ['types_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'code', name='uq_tiers_entreprise_code')
    )
    op.create_index(op.f('ix_tiers_code'), 'tiers', ['code'], unique=False)
    op.create_index(op.f('ix_tiers_niu'), 'tiers', ['niu'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'login', name='uq_utilisateurs_entreprise_login')
    )
    op.create_index(op.f('ix_utilisateurs_login'), 'utilisateurs', ['login'], unique=False)
    op.create_table('affectations_utilisateur_pdv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=False),
    sa.Column('est_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'point_de_vente_id', name='uq_affectations_utilisateur_pdv')
    )
    op.create_table('commandes_fournisseurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('numero_fournisseur', sa.String(length=50), nullable=True),
    sa.Column('date_commande', sa.Date(), nullable=False),
    sa.Column('date_livraison_prevue', sa.Date(), nullable=True),
    sa.Column('delai_livraison_jours', sa.Integer(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['etat_id'], ['etats_document.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_fournisseurs_numero'), 'commandes_fournisseurs', ['numero'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiers_id', sa.Integer(), nullable=False),
    sa.Column('civilite', sa.String(length=10), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('fonction', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('est_principal', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('reference_client', sa.String(length=80), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date_devis', sa.Date(), nullable=False),
    sa.Column('date_validite', sa.Date(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remise_globale_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remise_globale_montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=False),
    sa.Column('taux_change', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('conditions_generales', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['etat_id'], ['etats_document.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_numero'), 'devis', ['numero'], unique=False)
    op.create_table('ecritures_comptables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=True),
    sa.Column('date_ecriture', sa.Date(), nullable=False),
    sa.Column('numero_piece', sa.String(length=50), nullable=False),
    sa.Column('piece_jointe_ref', sa.String(length=255), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journaux_comptables.id'], ),
    sa.ForeignKeyConstraint(['periode_id'], ['periodes_comptables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=True),
    sa.Column('type_contrat_id', sa.Integer(), nullable=True),
    sa.Column('matricule', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=1), nullable=True),
    sa.Column('nationalite', sa.String(length=50), nullable=True),
    sa.Column('situation_familiale', sa.String(length=20), nullable=True),
    sa.Column('niu', sa.String(length=30), nullable=True),
    sa.Column('numero_cnps', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('salaire_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=True),
    sa.Column('compte_bancaire', sa.String(length=50), nullable=True),
    sa.Column('banque', sa.String(length=80), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['type_contrat_id'], ['types_contrat.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'matricule', name='uq_employes_entreprise_matricule')
    )
    op.create_index(op.f('ix_employes_matricule'), 'employes', ['matricule'], unique=False)
    op.create_index(op.f('ix_employes_niu'), 'employes', ['niu'], unique=False)
    op.create_index(op.f('ix_employes_numero_cnps'), 'employes', ['numero_cnps'], unique=False)
    op.create_table('journaux_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('entite_type', sa.String(length=80), nullable=True),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journaux_audit_action'), 'journaux_audit', ['action'], unique=False)
    op.create_index(op.f('ix_journaux_audit_entite_type'), 'journaux_audit', ['entite_type'], unique=False)
    op.create_index(op.f('ix_journaux_audit_module'), 'journaux_audit', ['module'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('entite_type', sa.String(length=80), nullable=True),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_entite_type'), 'notifications', ['entite_type'], unique=False)
    op.create_table('prix_produits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('canal_vente_id', sa.Integer(), nullable=True),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=True),
    sa.Column('prix_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('prix_ht', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canal_vente_id'], ['canaux_vente.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits_conditionnements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('conditionnement_id', sa.Integer(), nullable=False),
    sa.Column('quantite_unites', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('prix_vente_ttc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['conditionnement_id'], ['conditionnements.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variantes_produits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('prix_ttc_supplement', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stock_separe', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantes_produits_code'), 'variantes_produits', ['code'], unique=False)
    op.create_table('avances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('date_avance', sa.Date(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('rembourse', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletins_paie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('periode_paie_id', sa.Integer(), nullable=False),
    sa.Column('salaire_brut', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_gains', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_retenues', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_a_payer', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['periode_paie_id'], ['periodes_paie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'employe_id', 'periode_paie_id', name='uq_bulletins_paie_emp_periode')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date_commande', sa.Date(), nullable=False),
    sa.Column('date_livraison_prevue', sa.Date(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=False),
    sa.Column('reference_client', sa.String(length=80), nullable=True),
    sa.Column('adresse_livraison', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['etat_id'], ['etats_document.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_numero'), 'commandes', ['numero'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('taux_commission_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('payee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['taux_commission_id'], ['taux_commissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes_conge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_conge_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('nombre_jours', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('commentaire_refus', sa.String(length=255), nullable=True),
    sa.Column('approuve_par_id', sa.Integer(), nullable=True),
    sa.Column('date_decision', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approuve_par_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['type_conge_id'], ['types_conge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures_fournisseurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('commande_fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('numero_fournisseur', sa.String(length=50), nullable=False),
    sa.Column('type_facture', sa.String(length=20), nullable=False),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('montant_ht', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_restant_du', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=False),
    sa.Column('statut_paiement', sa.String(length=20), nullable=False),
    sa.Column('date_reception_facture', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commande_fournisseur_id'], ['commandes_fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_fournisseurs_numero_fournisseur'), 'factures_fournisseurs', ['numero_fournisseur'], unique=False)
    op.create_table('lignes_amortissement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('immobilisation_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('montant_dotation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cumul_amortissement', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valeur_nette', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ecriture_comptable_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecriture_comptable_id'], ['ecritures_comptables.id'], ),
    sa.ForeignKeyConstraint(['immobilisation_id'], ['immobilisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_ecritures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecriture_id', sa.Integer(), nullable=False),
    sa.Column('compte_id', sa.Integer(), nullable=False),
    sa.Column('libelle_ligne', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes_comptables.id'], ),
    sa.ForeignKeyConstraint(['ecriture_id'], ['ecritures_comptables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_mouvement', sa.String(length=20), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('depot_dest_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('lot_serie', sa.String(length=80), nullable=True),
    sa.Column('date_peremption', sa.Date(), nullable=True),
    sa.Column('date_mouvement', sa.DateTime(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['depot_dest_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectifs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('montant_cible', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('atteint', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commande_fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('numero_bl_fournisseur', sa.String(length=80), nullable=True),
    sa.Column('date_reception', sa.Date(), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commande_fournisseur_id'], ['commandes_fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptions_numero'), 'receptions', ['numero'], unique=False)
    op.create_table('soldes_conge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_conge_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('droits_acquis', sa.Integer(), nullable=False),
    sa.Column('jours_pris', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['type_conge_id'], ['types_conge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'employe_id', 'type_conge_id', 'annee', name='uq_soldes_conge_emp_type_annee')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unite_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['unite_id'], ['unites_mesure.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_produits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depot_id', 'produit_id', 'variante_id', name='uq_stocks_depot_produit_variante')
    )
    op.create_table('factures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=False),
    sa.Column('type_facture', sa.String(length=20), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_restant_du', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=False),
    sa.Column('mention_legale', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['etat_id'], ['etats_document.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_numero'), 'factures', ['numero'], unique=False)
    op.create_table('lignes_bulletin_paie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bulletin_paie_id', sa.Integer(), nullable=False),
    sa.Column('type_element_paie_id', sa.Integer(), nullable=True),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_paie_id'], ['bulletins_paie.id'], ),
    sa.ForeignKeyConstraint(['type_element_paie_id'], ['types_element_paie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bons_livraison',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('point_de_vente_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date_livraison', sa.Date(), nullable=False),
    sa.Column('contact_livraison', sa.String(length=150), nullable=True),
    sa.Column('adresse_livraison', sa.Text(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['tiers.id'], ),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['etat_id'], ['etats_document.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['point_de_vente_id'], ['points_de_vente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bons_livraison_numero'), 'bons_livraison', ['numero'], unique=False)
    op.create_table('reglements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('type_reglement', sa.String(length=20), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('facture_fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('tiers_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date_reglement', sa.Date(), nullable=False),
    sa.Column('date_valeur', sa.Date(), nullable=True),
    sa.Column('mode_paiement_id', sa.Integer(), nullable=False),
    sa.Column('compte_tresorerie_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['compte_tresorerie_id'], ['comptes_tresorerie.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['facture_fournisseur_id'], ['factures_fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['mode_paiement_id'], ['modes_paiement.id'], ),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reglements')
    op.drop_index(op.f('ix_bons_livraison_numero'), table_name='bons_livraison')
    op.drop_table('bons_livraison')
    op.drop_table('lignes_bulletin_paie')
    op.drop_index(op.f('ix_factures_numero'), table_name='factures')
    op.drop_table('factures')
    op.drop_table('stocks')
    op.drop_table('soldes_conge')
    op.drop_index(op.f('ix_receptions_numero'), table_name='receptions')
    op.drop_table('receptions')
    op.drop_table('objectifs')
    op.drop_table('mouvements_stock')
    op.drop_table('lignes_ecritures')
    op.drop_table('lignes_amortissement')
    op.drop_index(op.f('ix_factures_fournisseurs_numero_fournisseur'), table_name='factures_fournisseurs')
    op.drop_table('factures_fournisseurs')
    op.drop_table('demandes_conge')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_commandes_numero'), table_name='commandes')
    op.drop_table('commandes')
    op.drop_table('bulletins_paie')
    op.drop_table('avances')
    op.drop_index(op.f('ix_variantes_produits_code'), table_name='variantes_produits')
    op.drop_table('variantes_produits')
    op.drop_table('produits_conditionnements')
    op.drop_table('prix_produits')
    op.drop_index(op.f('ix_notifications_entite_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_journaux_audit_module'), table_name='journaux_audit')
    op.drop_index(op.f('ix_journaux_audit_entite_type'), table_name='journaux_audit')
    op.drop_index(op.f('ix_journaux_audit_action'), table_name='journaux_audit')
    op.drop_table('journaux_audit')
    op.drop_index(op.f('ix_employes_numero_cnps'), table_name='employes')
    op.drop_index(op.f('ix_employes_niu'), table_name='employes')
    op.drop_index(op.f('ix_employes_matricule'), table_name='employes')
    op.drop_table('employes')
    op.drop_table('ecritures_comptables')
    op.drop_index(op.f('ix_devis_numero'), table_name='devis')
    op.drop_table('devis')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_commandes_fournisseurs_numero'), table_name='commandes_fournisseurs')
    op.drop_table('commandes_fournisseurs')
    op.drop_table('affectations_utilisateur_pdv')
    op.drop_index(op.f('ix_utilisateurs_login'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_tiers_niu'), table_name='tiers')
    op.drop_index(op.f('ix_tiers_code'), table_name='tiers')
    op.drop_table('tiers')
    op.drop_index(op.f('ix_produits_code_barre'), table_name='produits')
    op.drop_index(op.f('ix_produits_code'), table_name='produits')
    op.drop_table('produits')
    op.drop_index(op.f('ix_postes_code'), table_name='postes')
    op.drop_table('postes')
    op.drop_table('permissions_roles')
    op.drop_index(op.f('ix_immobilisations_code'), table_name='immobilisations')
    op.drop_table('immobilisations')
    op.drop_index(op.f('ix_depots_code'), table_name='depots')
    op.drop_table('depots')
    op.drop_index(op.f('ix_types_element_paie_code'), table_name='types_element_paie')
    op.drop_table('types_element_paie')
    op.drop_index(op.f('ix_types_contrat_code'), table_name='types_contrat')
    op.drop_table('types_contrat')
    op.drop_index(op.f('ix_types_conge_code'), table_name='types_conge')
    op.drop_table('types_conge')
    op.drop_table('taux_commissions')
    op.drop_table('taux_change')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_points_de_vente_code'), table_name='points_de_vente')
    op.drop_table('points_de_vente')
    op.drop_table('periodes_paie')
    op.drop_table('periodes_comptables')
    op.drop_index(op.f('ix_parametres_systeme_cle'), table_name='parametres_systeme')
    op.drop_index(op.f('ix_parametres_systeme_categorie'), table_name='parametres_systeme')
    op.drop_table('parametres_systeme')
    op.drop_table('modes_paiement')
    op.drop_index(op.f('ix_licences_logicielles_cle_licence'), table_name='licences_logicielles')
    op.drop_table('licences_logicielles')
    op.drop_table('journaux_comptables')
    op.drop_index(op.f('ix_familles_produits_code'), table_name='familles_produits')
    op.drop_table('familles_produits')
    op.drop_index(op.f('ix_departements_code'), table_name='departements')
    op.drop_table('departements')
    op.drop_index(op.f('ix_conditionnements_code'), table_name='conditionnements')
    op.drop_table('conditionnements')
    op.drop_table('comptes_tresorerie')
    op.drop_index(op.f('ix_comptes_comptables_numero'), table_name='comptes_comptables')
    op.drop_table('comptes_comptables')
    op.drop_index(op.f('ix_categories_immobilisation_code'), table_name='categories_immobilisation')
    op.drop_table('categories_immobilisation')
    op.drop_index(op.f('ix_canaux_vente_code'), table_name='canaux_vente')
    op.drop_table('canaux_vente')
    op.drop_index(op.f('ix_unites_mesure_code'), table_name='unites_mesure')
    op.drop_table('unites_mesure')
    op.drop_index(op.f('ix_types_tiers_code'), table_name='types_tiers')
    op.drop_table('types_tiers')
    op.drop_index(op.f('ix_taux_tva_code'), table_name='taux_tva')
    op.drop_table('taux_tva')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_etats_document_type_document'), table_name='etats_document')
    op.drop_index(op.f('ix_etats_document_code'), table_name='etats_document')
    op.drop_table('etats_document')
    op.drop_index(op.f('ix_entreprises_niu'), table_name='entreprises')
    op.drop_index(op.f('ix_entreprises_code'), table_name='entreprises')
    op.drop_table('entreprises')
    op.drop_index(op.f('ix_devises_code'), table_name='devises')
    op.drop_table('devises')
    # ### end Alembic commands ###
